name: Build

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Get dependencies
        run: go mod download

      - name: Build
        run: go build -v ./...

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: http-scanner
          path: ./http-scanner
